name: "Label issue from body keyword"
on:
  issues:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["https://ellie-app.com/"]'
          labels: '["has-ellie"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
