name: Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  testing:
    runs-on: ubuntu-latest

    steps:   
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 10
        
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install
      run: npm ci
    
    - name: Elm test suite
      run: npm run test
    
    - uses: webfactory/ssh-agent@v0.2.0
      with:
          ssh-private-key: ${{ secrets.ELM_UI_TESTING_SSH_PRIVATE_KEY }}
        
    - name: Rendering test suite on saucelabs
      run: npm run test-render-sauce-automated -- --build=2.0.0 --name=development
      env:
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
