name: Make Release Candidate

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.8'  # Specify GHC version
        cabal-version: '3.10'  # Specify Cabal version

    # Add steps here to build your Haskell project using Cabal
    - name: Build Project
      shell: bash
      run: |
        cp cabal.project.freeze.ghc92 cabal.project.freeze
        cp cabal.project.prod cabal.project
        cabal update
        cabal build # We use build instead of install because of a weird changeWorkingDirectory error when we do that, something to do with Elm's use of TH
        OUTPUT_BIN=$(cabal list-bin zokka)
        mkdir -p output
        cp $OUTPUT_BIN output/zokka

    # Extract the current git tag
    - name: Extract Git Tag
      id: get_version
      run: echo "##[set-output name=tag;]$(git describe --tags --abbrev=0)"

    # Upload artifacts
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zokka-compiler-ubuntu-x86_64-${{ steps.get_version.outputs.tag }}
        path: ./output/zokka

    - if: ${{ matrix.os == 'macos-latest' }}
      name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zokka-compiler-macos-x86_64-${{ steps.get_version.outputs.tag }}
        path: ./output/zokka

    - if: ${{ matrix.os == 'windows-latest' }}
      name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zokka-compiler-windows-x86_64-${{ steps.get_version.outputs.tag }}
        path: ./output/zokka
