name: Make Release Candidate

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.8'  # Specify GHC version
        cabal-version: '3.10'  # Specify Cabal version

    # Add steps here to build your Haskell project using Cabal
    - name: Build Project
      run: |
        cp cabal.project.freeze.ghc92 cabal.project.freeze
        cabal update
        mkdir -p output
        cabal install --installdir="./output/"

    # Extract the current git tag
    - name: Extract Git Tag
      id: get_version
      run: echo "##[set-output name=tag;]$(git describe --tags --abbrev=0)"

    # Upload artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zelm-compiler-${{ steps.get_version.outputs.tag }}
        path: ./output/zelm
